version: '3.8'
services:
    telegram-game-update-mailer:
        build:
            context: .
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        restart: always
        command: bash -c "/code/wait-for-it/wait-for-it.sh db:5432 --timeout=600 --strict -- python main.py"
        volumes:
          - ./logs:/code/logs/
        environment:
          - BOT_API_TOKEN=
          - LOG_LEVEL=
          - UPDATE_FREQUENCY=
          - POSTGRES_DB=
          - POSTGRES_USER=
          - POSTGRES_PASSWORD=
        depends_on:
            - db
    db:
        image: postgres:13.1
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        restart: always
        volumes:
            - ./databases/postgre:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=
            - POSTGRES_USER=
            - POSTGRES_PASSWORD=